#ifndef GUI_SHADERS_HPP
#define GUI_SHADERS_HPP

const char* defaultTextVertexShaderCode = ""
"#version 410\n"
"\n"
"layout(location = 0) in vec3 vertexPos;\n"
"layout(location = 1) in vec2 vertexUv;\n"
"\n"
"layout(location = 0) out vec2 fragUv;\n"
"\n"
"uniform mat4 viewProjMatrix;\n"
"uniform mat4 worldMat;\n"
"\n"
"void main() {\n"
"	fragUv = vertexUv;\n"
"	gl_Position = viewProjMatrix * vec4((vec4(vertexPos, 1.0) * worldMat).xyz, 1.0);\n"
"}\n"
"\n";

const char* defaultTextGeomentryShaderCode = ""
"#version 410\n"
"\n"
"layout(triangles) in;\n"
"layout(triangle_strip, max_vertices = 3) out;\n"
"\n"
"layout(location = 0) in vec2 fragUv[];\n"
"\n"
"layout(location = 0) out vec2 UV;\n"
"\n"
"void main() {\n"
"\n"
"	UV = fragUv[0];\n"
"	gl_Position = gl_in[0].gl_Position;\n"
"	EmitVertex();\n"
"\n"
"	UV = fragUv[1];\n"
"	gl_Position = gl_in[1].gl_Position;\n"
"	EmitVertex();\n"
"\n"
"	UV = fragUv[2];\n"
"	gl_Position = gl_in[2].gl_Position;\n"
"	EmitVertex();\n"
"	EndPrimitive();\n"
"\n"
"}\n";

const char* defaultTextFragmentShaderCode = ""
"#version 410\n"
"\n"
"layout(location = 0) in vec2 TexCoords;\n"
"\n"
"layout(location = 0) out vec4 fragmentColor;\n"
"layout(location = 1) out vec4 red;\n"
"\n"
"uniform sampler2D text;\n"
"uniform vec3 textColor;\n"
"\n"
"void main() {\n"
"vec4 sampled = vec4(1.0, 1.0, 1.0, texture(text, TexCoords).r);\n"
"fragmentColor = vec4(textColor, 1.0) * sampled;\n"
"red = vec4(1.0);\n"
"}\n"
"\n";

const char* defaultPassthroughVertexShaderCode = ""
"#version 410\n"
"\n"
"layout(location = 0) in vec3 vertexPos;\n"
"layout(location = 1) in vec2 vertexUv;\n"
"\n"
"void main() {\n"
"	gl_Position = vec4(vertexPos, 1.0);\n"
"}\n"
"\n";

const char* defaultPointToQuadGeomentryShaderCode = ""
"#version 410\n"
"\n"
"layout(points) in;\n"
"layout(triangle_strip, max_vertices = 6) out;\n"
"\n"
"layout(location = 0) out vec2 UV;\n"
"\n"
"uniform mat4 viewProjMatrix;\n"
"uniform mat4 worldMat;\n"
"\n"
"void main() {\n"
"\n"
"   vec4 p0 = worldMat[0];"
"   vec4 p1 = worldMat[1];"
"   vec4 p2 = worldMat[2];"
"   vec4 p3 = worldMat[3];"
"\n"
"	gl_Position = viewProjMatrix * vec4(p0.xy, 0.0, 1.0);\n"
"	UV = p0.zw;\n"
"	EmitVertex();\n"
"\n"
"	gl_Position = viewProjMatrix * vec4(p1.xy, 0.0, 1.0);\n"
"	UV = p1.zw;\n"
"	EmitVertex();\n"
"\n"
"	gl_Position = viewProjMatrix * vec4(p2.xy, 0.0, 1.0);\n"
"	UV = p2.zw;\n"
"	EmitVertex();\n"
"	EndPrimitive();\n"
"\n"
"	gl_Position = viewProjMatrix * vec4(p0.xy, 0.0, 1.0);\n"
"	UV = p1.zw;\n"
"	EmitVertex();\n"
"\n"
"	gl_Position = viewProjMatrix * vec4(p2.xy, 0.0, 1.0);\n"
"	UV = p2.zw;\n"
"	EmitVertex();\n"
"\n"
"	gl_Position = viewProjMatrix * vec4(p3.xy, 0.0, 1.0);\n"
"	UV = p3.zw;\n"
"	EmitVertex();\n"
"	EndPrimitive();\n"
"\n"
"}\n";

const char* defaultQuadFragmentShaderCode = ""
"#version 410\n"
"\n"
"layout(location = 0) in vec2 TexCoords;\n"
"\n"
"layout(location = 0) out vec4 fragmentColor;\n"
"\n"
"uniform sampler2D tex;\n"
"\n"
"void main() {\n"
"vec4 sampled = texture(tex, TexCoords);\n"
"fragmentColor = sampled;\n"
"}\n"
"\n";

#endif